name: Test Formula

on:
  pull_request:
    paths:
      - 'Formula/**'
  push:
    branches:
      - main
    paths:
      - 'Formula/**'
  workflow_dispatch:

jobs:
  check_pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: suzuki-shunsuke/pinact-action@d735505f3decf76fca3fdbb4c952e5b3eba0ffdd # v0.1.2
        with:
          skip_push: "true"

  test-formula:
    needs: [check_pinact]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@866b91cc020931c510d42e43e498a7f07d335f60 # v1.259.0
        with:
          ruby-version: '3.4.6'
          bundler-cache: false

      - name: Verify Formula syntax
        run: |
          # Basic Ruby syntax check
          ruby -c Formula/techscan.rb
          echo "✅ Formula syntax is valid"

      - name: Verify Formula structure
        run: |
          # Check required Formula components
          if ! grep -q "class Techscan < Formula" Formula/techscan.rb; then
            echo "❌ Formula class definition not found"
            exit 1
          fi
          if ! grep -q "def install" Formula/techscan.rb; then
            echo "❌ Install method not found"
            exit 1
          fi
          if ! grep -q "sha256" Formula/techscan.rb; then
            echo "❌ SHA256 checksums not found"
            exit 1
          fi
          echo "✅ Formula structure is valid"

      - name: Test URL accessibility
        run: |
          # Extract and test URLs from Formula
          VERSION=$(awk -F '"' '/version[[:space:]]+/ {print $2; exit}' Formula/techscan.rb)
          echo "Testing URLs for version: $VERSION"

          # Test darwin-arm64 URL
          URL="https://github.com/kimulaco/techscan/releases/download/v${VERSION}/techscan-darwin-arm64.tar.gz"
          if curl -f -s -I "$URL" > /dev/null; then
            echo "✅ Darwin ARM64 URL accessible: $URL"
          else
            echo "❌ Darwin ARM64 URL not accessible: $URL"
            exit 1
          fi

          # Test darwin-x64 URL
          URL="https://github.com/kimulaco/techscan/releases/download/v${VERSION}/techscan-darwin-x64.tar.gz"
          if curl -f -s -I "$URL" > /dev/null; then
            echo "✅ Darwin x64 URL accessible: $URL"
          else
            echo "❌ Darwin x64 URL not accessible: $URL"
            exit 1
          fi

          # Test linux-x64 URL
          URL="https://github.com/kimulaco/techscan/releases/download/v${VERSION}/techscan-linux-x64.tar.gz"
          if curl -f -s -I "$URL" > /dev/null; then
            echo "✅ Linux x64 URL accessible: $URL"
          else
            echo "❌ Linux x64 URL not accessible: $URL"
            exit 1
          fi
